version: '3.7'

services:
  discordbot:
    build: .
    container_name: kingcroc-bot
    environment:
      - TOTAL_SHARDS=1
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - DB_HOST=postgres
    ports:
      - "8000:8000"

  postgres:
    container_name: king-croc-postgresdb
    image: postgres:10.5
    restart: on-failure
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=db_user
      - APP_DB_PASS=password
      - APP_DB_NAME=king-croc
    volumes:
      - ./docker-db-scripts:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  pgadmin:
    container_name: king-croc-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: on-failure

volumes:
    postgres:
    pgadmin: